### ISSUE TITLE
Can't uninstall 

### ISSUE THREAD

**Issue by bifan** [maggie-chen/eslint-rules-zh-plugin#1]
![image](https://user-images.githubusercontent.com/2929293/111937363-87d4d580-8b02-11eb-8a23-b89faecea483.png)

**Comment by maggie-chen** [comment]
需要优先安装官方eslint插件

**Comment by bifan** [comment]
找到原因了，得先卸载“Web Dev Pack (JS/HTML/CSS)”这个插件（同时会删除ESlint）
![image](https://user-images.githubusercontent.com/2929293/111938342-ad62de80-8b04-11eb-9f40-207c88699bbf.png)
